[package]
name = "rust_game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "*"
bevy_prototype_debug_lines = "*"

# Enable a small amount of optimization in debug builds
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies
[profile.dev.package."*"]
opt-level = 3